"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - front_left_hip_joint
          - front_left_upper_leg_joint
          - front_left_lower_leg_joint
          - front_right_hip_joint
          - front_right_upper_leg_joint
          - front_right_lower_leg_joint
          - rear_left_hip_joint
          - rear_left_upper_leg_joint
          - rear_left_lower_leg_joint
          - rear_right_hip_joint
          - rear_right_upper_leg_joint
          - rear_right_lower_leg_link

      gains:
        front_left_hip_joint : {p: 180, d: 0.9, i: 20}
        front_left_upper_leg_joint : {p: 180, d: 0.9, i: 20}
        front_left_lower_leg_joint : {p: 180, d: 0.9, i: 20}
        front_right_hip_joint : {p: 180, d: 0.9, i: 20}
        front_right_upper_leg_joint : {p: 180, d: 0.9, i: 20}
        front_right_lower_leg_joint : {p: 180, d: 0.9, i: 20}
        rear_left_hip_joint : {p: 180, d: 0.9, i: 20}
        rear_left_upper_leg_joint : {p: 180, d: 0.9, i: 20}
        rear_left_lower_leg_joint : {p: 180, d: 0.9, i: 20}
        rear_right_hip_joint : {p: 180, d: 0.9, i: 20}
        rear_right_upper_leg_joint : {p: 180, d: 0.9, i: 20}
        rear_right_lower_leg_link : {p: 180, d: 0.9, i: 20}
