base: base_link
left_front:
  - front_left_hip_link
  - front_left_upper_leg_link
  - front_left_lower_leg_link
  - front_left_foot_link

right_front:
  - front_right_hip_link
  - front_right_upper_leg_link
  - front_right_lower_leg_link
  - front_right_foot_link

left_hind:
  - rear_left_hip_link
  - rear_left_upper_leg_link
  - rear_left_lower_leg_link
  - rear_left_foot_link

right_hind:
  - rear_right_hip_link
  - rear_right_upper_leg_link
  - rear_right_lower_leg_link
  - rear_right_foot_link